version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "checkin"
      POSTGRES_PASSWORD: "checkin"
      POSTGRES_DB: "check_in"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
